### ISSUE TITLE
Why is debounce and throttle depracated

### ISSUE THREAD

**Issue by graysheeep** [jayphelps/core-decorators#144]
I think these two decorators useful, so why remark then as depracated?

**Comment by toxic-johann** [comment]
> Things like debouncing, throttling, and other more opinionated decorators are being phased out in favor of lodash-decorators which wraps applicable lodash utilities as decorators. We don't want to duplicate the effort of lodash, which has years and years of robust testing and bugfixes.

According to [Need lodash utilities as decorators?](https://github.com/jayphelps/core-decorators#need-lodash-utilities-as-decorators)

**Comment by jayphelps** [comment]
Yep @toxic-johann is right. We found ourselves fixing bugs and adding features that have long since existed in lodash, so duplicating the effort wasn't a good idea. [lodash-decorators](https://github.com/steelsojka/lodash-decorators) wraps lodash providing them as decorators, so it's the suggested way to go moving forward. I think this is great for everyone.

Hope this makes sense!

**Comment by cyl19910101** [comment]
@jayphelps That does make sense, but I think you should point it out the reason in README, otherwise people like me might think in other ways (For example: is it because it's a bad idea to use those functions here). 🤣  Thanks a lot for your works, it's cool!
