### ISSUE TITLE
Why is mixin deprecated?

### ISSUE THREAD

**Issue by AjaxSolutions** [jayphelps/core-decorators#145]
I wish there was brief note explaining why the mixin decorator was deprecated.

**Comment by jayphelps** [comment]
Sorry for the confusion and not making it clearer! I added an [explanation in the deprecation message](https://github.com/jayphelps/core-decorators/commit/74615e2c349b827a346e60c110673dbe443800b6#diff-e668005854c7b42f6b172bf9ffb994fbR52) `@mixin is deprecated and will be removed shortly. Use @mixin from lodash-decorators.` and [there's a blurb in the README](https://github.com/jayphelps/core-decorators#need-lodash-utilities-as-decorators) but it indeed isn't super clear since it doesn't specifically say it's about the deprecated ones.

https://www.npmjs.com/package/lodash-decorators#mixin

I'll see if I can come up with a better disclaimer. Thanks for letting me know!

**Comment by tombh** [comment]
I was curious about this too, so I searched "mixin" in the issues here to get the context. I'm thinking about using this lib so I've never seen that warning message. So yeah a note in the README about preferring lodash's decorator would be useful.
